import os

DB_TYPE = os.getenv("DB_TYPE", "json_file")
SESSION_STORE_TYPE = os.getenv("SESSION_STORE_TYPE", "json_file")
MIN_USERNAME_LENGTH = 3
MAX_USERNAME_LENGTH = 30
MIN_PASSWORD_LENGTH = 6
MAX_PASSWORD_LENGTH = 50
BUILT_IN_ROLES = ["ADMIN", "OBSERVER"]
SESSION_STORE_JSON_FILE_PATH = "sessions.json"
SESSION_EXPIRY_SECONDS = 3600  # 1 hour